[workspace]
members = [
    "packages/*",
    "contracts/core/pool",
    "contracts/core/adapters/anchor",
    "contracts/mocks/adapter",
    "contracts/mocks/market",
]

[profile.release]
rpath = false
lto = true
overflow-checks = true
